---
title: "DRuID"
author: "Adam H Sparks and Ricardo Oliva"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DRuID}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# DRuID: An informed-Decision platform to reduce the risk of RIce Diseases 

## Description

In ancient times, druids were knowledge-keepers that provided members of the society with advice on health matters. In the same way, we are proposing to implement a web platform to advise decision-makers on which rice varieties should be promoted next season to keep a healthy crop. The tool will allow managing disease in real-time and to define breeding priorities for specific regions. In order to do that, the platform will integrated early-season pathogen diagnostics, modeling of weather patterns, and rice disease resistance profiles of local rice varieties. The platform can give an advice after solving three main questions:

- What is the predominant pathogen population on the area?

- Which areas have higher risk of disease?

- What is the resistance spectrum that is needed for that area?

We expect that the tool will allow public and private enterprises to make informed-decision on rice. To feed the DRUiD platform with field and environment data, we have developed new technologies that will be integrated for the first time. For instance, we created PathoTracer, a molecular test that can identify pathogen races directly from an infected leaf sample. We are also building a catalog of resistance factors in released varieties to determine the best fit.

## The need

Rice diseases, such as bacterial leaf blight, represent a serious limitation for rice production in most areas of Asia. The disease prevails in the paddy because farmers use susceptible varieties where weather conditions favor disease development. In that scenario, the risk of having an outbreak the next season is higher.

## Impact

We expect to empower rice farmers by providing seasonal advice. If farmers know which variety is less likely to suffer in the following season, it will reduce the risk and increases its income. Up scaling this principle can result in effective management of large rice areas or targeting breeding by national programs working in rice.

## Contact details

Associate Professor Adam H. Sparks, University of Southern Queensland (USQ)

  - [adam.sparks@usq.edu.au](mailto::adam.sparks@usq.edu.au)
  
  - [orcid.org/0000-0002-0061-8359](https://orcid.org/0000-0002-0061-8359)

Dr. Ricardo Oliva, International Rice Research Institute (IRRI)
